system:
  mode: 1 # 0 for graph mode, 1 for pynative mode in mindspore
  amp_level: 'O0'
  seed: 42

preprocess:
  path:
    checkpoint_dir: "./checkpoints/"
    path_of_net_recon_model: 'ms/ms_net_recon.ckpt'
    dir_of_bfm_fitting: 'BFM_Fitting'

audio2exp:
  path:
    checkpoint_dir: "./checkpoints/"
    # inference
    audio2exp_checkpoint: 'ms/ms_audio2exp.ckpt'
    # train
    wav2lip_checkpoint: 'wav2lip.pth'

  model:
    audioencoder:
      leaky_relu: True
      norm: 'in'
    discriminator:
      leaky_relu: false
      input_channels: 6
    cvae:
      audio_emb_in_size: 512
      audio_emb_out_size: 128
      seq_len: 32
      latent_size: 256
      encoder_layer_sizes: [192, 1024]
      decoder_layer_sizes: [1024, 192]

audio2pose:
  path:
    checkpoint_dir: "./checkpoints/"
    audio2pose_checkpoint: 'ms/ms_audio2pose.ckpt'

  dataset:
    num_classes: 46

  model:
    audioencoder:
      leaky_relu: True
      norm: 'in'
    discriminator:
      leaky_relu: false
      input_channels: 6
    cvae:
      audio_emb_in_size: 512
      audio_emb_out_size: 6
      seq_len: 32
      latent_size: 64
      encoder_layer_sizes: [192, 128]
      decoder_layer_sizes: [128, 192]

facerender:
  path:
    checkpoint_dir: "./checkpoints/"
    mappingnet_checkpoint: 'ms/ms_mapping.ckpt'
    generator_checkpoint: 'ms/ms_generator.ckpt'
    kp_extractor_checkpoint: 'ms/ms_kp_extractor.ckpt'
    he_estimator_checkpoint: 'ms/ms_he_estimator.ckpt'

  model_params:
    common_params:
      num_kp: 15
      image_channel: 3
      feature_channel: 32
      estimate_jacobian: false   # True
    kp_detector_params:
      temperature: 0.1
      block_expansion: 32
      max_features: 1024
      scale_factor: 0.25         # 0.25
      num_blocks: 5
      reshape_channel: 16384  # 16384 = 1024 * 16
      reshape_depth: 16
    he_estimator_params:
      block_expansion: 64
      max_features: 2048
      num_bins: 66
    generator_params:
      block_expansion: 64
      max_features: 512
      num_down_blocks: 2
      reshape_channel: 32
      reshape_depth: 16         # 512 = 32 * 16
      num_resblocks: 6
      estimate_occlusion_map: True
      dense_motion_params:
        block_expansion: 32
        max_features: 1024
        num_blocks: 5
        reshape_depth: 16
        compress: 4
    discriminator_params:
      scales: [1]
      block_expansion: 32
      max_features: 512
      num_blocks: 4
      sn: True
    mapping_params:
        coeff_nc: 70 # 73 if under 'full' preprocess
        descriptor_nc: 1024
        layer: 3
        num_kp: 15
        num_bins: 66

  train:
    pretrained_vgg: /disk1/katekong/sadtalker/checkpoints/ms/ms_vgg19.ckpt
    pretrained_hopenet: /disk1/katekong/sadtalker/checkpoints/ms/ms_hopenet_robust_alpha1.ckpt
    transform_params:
      sigma_affine: 0.05
      sigma_tps: 0.005
      points_tps: 5
    loss_weights:
      generator_gan: 1
      discriminator_gan: 1
      feature_matching: [10, 10, 10, 10]
      perceptual: [10, 10, 10, 10, 10]
      equivariance_value: 10
      equivariance_jacobian: 0    # 10
      keypoint: 10
      headpose: 20
      expression: 5
